---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: tests/phpcs-ruleset.xml
      ignore_warnings: true
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: "codesize,design,naming,unusedcode"
ratings:
  paths:
    - "**.php"
exclude_paths:
  - tests/**/*
