language: php
php:
    - 5.5
    - 5.6
install:
    - composer self-update
    - composer install
script:
    - ./bin/phpunit
    - ./bin/phpcs --standard=tests/phpcs-ruleset.xml app lib tests
    - ./bin/phpmd app,lib,tests text codesize,design,naming,unusedcode
